version: '3.8'
services:
  postgres:
    image: postgres:15.7-alpine
    container_name: postgres_con
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\Egemen\CODING\DockerContainers:/var/lib/postgresql/data

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app_con
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_con:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    ports:
      - "8082:8082"
    depends_on:
      - postgres
